create architecture
Feelini/kiparo pull request #3
Opened 2021-08-24 13:58 UTC by Feelini

2021-08-26 18:14 UTC, tim-teacher requested changes

2021-08-26 18:14 UTC, tim-teacher commented on Covid/.idea/misc.xml
> +  <component name="DesignSurface">
.idea лучше в git ignore добавить.

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/domain/models/CovidCountryInfo.kt
> +data class CovidCountryInfo(
Убрать null.

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/domain/usecase/GetCovidInfoUseCase.kt
> +class GetCovidInfoUseCase {
В окнструктор передать объект репозитория. Вернуть правильные данные, пометить execute() как suspend.

```
suspend fun execute(): CovidInfo{
        return covidRepository.getCovidInfo();
    }
```

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/data/api/NetworkService.kt
> +    val apiService: JSONPlaceHolderApi = getRetrofit().create(JSONPlaceHolderApi::class.java)
```
val apiService by lazy {
  getRetrofit().create(JSONPlaceHolderApi::class.java)
}
```

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/MainActivity.kt
> +            ViewModelProvider(this, ViewModelFactory(ApiHelper(NetworkService.apiService)))
Во VM нужно передавать объект Use Case и больше ничего.

```
val apiHelper = ApiHelper(NetworkService.apiService);
val repository = CovidRepositoryImpl(apiHelper);
val useCase = GetInfoUseCase(repository);

viewModel =
            ViewModelProvider(this, ViewModelFactory(useCase))
```

```
object UseCaseProvider() {
   fun provideUseCase() {
      val apiHelper = ApiHelper(NetworkService.apiService);
       val repository = CovidRepositoryImpl(apiHelper);
       val useCase = GetInfoUseCase(repository);
      return useCase;
   }
}
```

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/MainActivity.kt
> +            .replace(R.id.fragment_container, InfoFragment(covidInfo))
В конструктор фрагмента ничего передавать нельзя.

Если вдруг нужно что то передать в фрагмент:
val fragment = InfoFragment();
Bundle bundle= new Budnle()
fragment.setArgument(bundle)

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/MainActivityViewModel.kt
> +    fun getCovidInfo() = liveData(Dispatchers.IO){
Вместо` fun getCovidInfo() ` = 

`val covidInfo = liveData(Dispatchers.IO){.....`

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/InfoFragment.kt
> +        val simpleDateFormat = SimpleDateFormat("dd MMM, yyyy")
Вынести в отдельный статик метод(в котлине это просто метод внутри файла без объявления класса).

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/InfoFragment.kt
> +        infoListAdapter = InfoListAdapter(infoList = infoList)
Адаптер создать в самом верху класса один раз на весь фрагмент, а данные в него закидывать через метод.

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/utils/Resource.kt
> +data class Resource<out T>(val status: Status, val data: T?, val message: String?) {
Нужно поменять на sealed class.

```
seald class Result {
   Success(data: CovidInfo) : Result;
   Error(error: Trhorawable) : Result;
   Loading() : Result;
}
```

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/utils/Status.kt
> +enum class Status {
Этот енам не нужен.

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/utils/ViewModelFactory.kt
> +class ViewModelFactory(private val apiHelper: ApiHelper): ViewModelProvider.Factory {
Входящие параметры убираем.

2021-08-26 18:14 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/utils/ViewModelFactory.kt
> +            return MainActivityViewModel(CovidRepositoryImpl(apiHelper)) as T
return MainActivityViewModel(UseCaseProvider().provideUseCase()) as T

2021-08-30 08:24 UTC, Feelini commented
Только не знаю, как сделать так, чтобы данные каждый раз не запрашивались при переключении по меню. Все время приходится ждать, пока придут данные.

2021-09-01 07:13 UTC, tim-teacher commented
> Только не знаю, как сделать так, чтобы данные каждый раз не запрашивались при переключении по меню. Все время приходится ждать, пока придут данные.

Это исправиться когда мы внедрим MVVM, будет одна viewModel которая шариться между фрагментами.

2021-09-01 07:31 UTC, tim-teacher requested changes

2021-09-01 07:31 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/data/api/JSONPlaceHolderApi.kt
> +    @Headers("Vary1: dfgfdsg4358ou9h48ihkdsjfhds")
Давай этот header в константу вынесем.

2021-09-01 07:31 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/MainActivity.kt
> +    private fun addInfoFragment() {
префикс add немного смущает меня, давай на replace поменяем, а то сразу в мыслях думаешь что фрагмент именно добавляется командой add, а не replace.

2021-09-01 07:31 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/infolist/InfoFragment.kt
> +                .get(MainActivityViewModel::class.java)
VM должна быть одна на оба фрагмента, а у тебя создается отдельно для каждого. Что-бы была общая VM нужно создавать ее в методе onActivityCreated() и вместо this использовать ссылку на активити, тоесть getActivity().

2021-09-01 07:31 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/infolist/InfoFragment.kt
> +        infoListView.adapter = infoListAdapter
infoListView.adapter = infoListAdapter нужно один раз сделать когда создается экран, в showInfoList не нужно его вызывать каждый раз, ты просто меняешь данные, а адаптер уже и так находится внутри ресайкла.

2021-09-01 07:31 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/infolist/InfoFragment.kt
> +        infoListView.layoutManager = LinearLayoutManager(context, RecyclerView.VERTICAL, false)
Тут тоже самое.

2021-09-01 07:31 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/infolist/InfoListAdapter.kt
> +        infoCountryList = infoList
После `infoCountryList = infoList ` нужно вызвать notifyDataSetChanged().

2021-09-03 14:47 UTC, tim-teacher commented on Covid/.idea/misc.xml
> +  <component name="DesignSurface">
все еще есть папка .idea.

2021-09-03 22:36 UTC, tim-teacher requested changes

2021-09-03 22:36 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/infolist/InfoListAdapter.kt
> +        fun bindData(covidCountryInfo: CovidCountryInfo) {
метод  bing вызывается каждый раз как нужно показать что то в одной строчке. Но весь смысл холдеры это вызывать findViewById как можно реже, тоесть кешировать их. findViewById нужно делать в конструкторе холдера, а вот в bind только использовать готовые переменные.

2021-09-03 22:36 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/data/api/JSONPlaceHolderApi.kt
> +import com.soldatov.covid.domain.models.CovidInfo
ммм, не хотелось бы аж отсюда иметь доступ к моделям домена. Да еще и если там названия переменных поменяются у нас тут при парсинге будет проблема. Давай у домена свои модельки сделаем, а в репозитории замапим их в доменовские.

2021-09-06 12:52 UTC, Feelini commented on Covid/.idea/misc.xml
> +  <component name="DesignSurface">
я так понимаю, это из-за того, что файл изначально был добавлен в гит. теперь я прописал везде папку идея в гитигнор, но он все равно чекает изменения

2021-09-09 09:45 UTC, tim-teacher requested changes

2021-09-09 09:45 UTC, tim-teacher commented on Covid/.idea/misc.xml
> +  <component name="DesignSurface">
Да, просто ее нужно удалить и сделать коммит, что бы гит у себя ее удалил. А потом переоткрыть проект в студии что бы студия создала его либо просто прям в гит хабе удалить их.

2021-09-09 09:45 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/data/repository/CovidRepositoryImpl.kt
> +            }
Это все можно упростить использую последовательности:
```
val domainCountryInfoList = covidInfo.china.data
            .filter { it.lat != null && it.long != null }
            .map { it.toDomain() }
            
return DomainCovidInfo( ......
``` 
```
  extension CovidCountryInfo.toDomain() : DomainCovidInfo {
      return DomainCountryInfo(it.country, it.lat, it.long, it.confirmed)
  }          
           
``` 

А можно и еще екстенщен для `CovidInfo`. Что бы в методе `getCovidInfo()` чисто написать:
```
 val covidInfo = apiHelper.getCovidInfo()
 return covidInfo.toDomain()
```

2021-09-09 09:45 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/data/repository/CovidRepositoryImpl.kt
> +            }
Я бы конечно упростил для домена модельку. У нас в дата есть CovidInfo, в ней ChinaInfo, а в ней CovidCountryInfo.
Я бы сделал одну модельку со всеми нужными данными и в ней массив CovidCountryInfo. Тоесть CovidInfo и ChinaInfo объединилбы в одну. А во вторых даты в милисекундах нужно положить в Date что бы не передавать long в домен, там уже должно быть все строго, если это дата то должна бать дата.

2021-09-09 09:45 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/infolist/InfoFragment.kt
> +        infoListView.layoutManager = LinearLayoutManager(context, RecyclerView.VERTICAL, false)
настройку адаптера лучше перенеси в onViewCreated. Тут нам только VM нужно создать, а остальное пусть будет как положено.

2021-09-09 09:45 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/map/MapFragment.kt
> +    private lateinit var covidInfo: DomainCovidInfo
Никаких данных в фрагмент быть не должно, это только в VM.

2021-09-09 09:45 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/map/MapFragment.kt
> +                    mapFragment.getMapAsync(this)
Я бы запускал карту сразу, что бы не терять время на загрузску данных, пусть она инициализируется. А вот как только данные пришли нужно проверить если карта готова то показать данные, если нет, то как только срабатывает onMapReady, мы берем данные из VM и показываем.

2021-09-09 09:45 UTC, tim-teacher commented on Covid/app/src/main/java/com/soldatov/covid/presentation/map/MapFragment.kt
> +        covidInfo.countryInfoList.forEach {
Хорошо бы в от дельный метод это все закинуть. Имею ввиду добавление маркеров.

2021-09-13 12:12 UTC, tim-teacher approved these changes

2021-09-14 06:11 UTC, merged