taxi app
Feelini/kiparo pull request #6
Opened 2021-09-03 12:25 UTC by Feelini

2021-09-09 10:02 UTC, tim-teacher requested changes

2021-09-09 10:02 UTC, tim-teacher commented on Taxi/app/src/main/java/com/soldatov/taxi/presentation/ui/MainActivity.kt
> +    private lateinit var taxiInfo: List<DomainTaxiInfo>
Данные из активити удаляем, тут им не место.

2021-09-09 10:02 UTC, tim-teacher commented on Taxi/app/src/main/java/com/soldatov/taxi/presentation/ui/MainActivity.kt
> +                    mapView.getMapAsync(this)
Тут тоже замечание что и в короне апп, нужно сразу карту стартовать.

2021-09-09 10:02 UTC, tim-teacher commented on Taxi/app/src/main/java/com/soldatov/taxi/presentation/ui/MainActivity.kt
> +        p0.uiSettings.isZoomControlsEnabled = false
p0 очень старрное имя переменной ;)

2021-09-09 10:02 UTC, tim-teacher commented on Taxi/app/src/main/java/com/soldatov/taxi/presentation/ui/TaxiListFragment.kt
> +        if (context is TaxiListAdapter.OnTaxiClickListener){
Ой ты что)) так делали 10 лет назад в андроид. А сейчас у нас есть VM через которую и нужно отправлять данные. Тоесть тут нажали на такси, и дернули метод в VM. А вот VM пусть и уведомляет кого нужно о том что мы выделили такси конкретную и нужно на нее сфокусироваться.

2021-09-09 10:54 UTC, Feelini commented on Taxi/app/src/main/java/com/soldatov/taxi/presentation/ui/TaxiListFragment.kt
> +        if (context is TaxiListAdapter.OnTaxiClickListener){
меня так на курсах учили))

2021-09-13 12:30 UTC, tim-teacher approved these changes

2021-09-14 06:05 UTC, merged